### ISSUE TITLE
Following Cursor

### ISSUE THREAD

**Issue by farzadso** [ShubhamVerma1811/vscode-react-outline#19]
The VSCode settings for outline include a "Follow Cursor" option.

When used, it doesn't follow the outline you created.

Is it fixable?

**Comment by ShubhamVerma1811** [comment]
Hi, yes I am aware of this issue.
I think this is happening because the TS/JS outline takes precedence of the cursor position rather than the React outline.

With the current code implementation, I don't think it's fixable (or maybe I am missing something).

I might have to change the approach as pointed out in #17, which might fix this issue and many other issues too.

**Comment by farzadso** [comment]
Cool. I hope you find the time to make such changes. I appreciate the effort you put into your extension.

Good luck.
